name: Build ciadpi for Lexra
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Environment
        run: |
          # Принудительно очищаем папку от остатков старых сборок
          rm -rf *

      - name: Download ByeDPI Archive
        run: |
          mkdir -p src
          curl -L "https://github.com" -o byedpi.tar.gz
          tar -xzf byedpi.tar.gz -C src --strip-components=1

      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mips-linux-gnu

      - name: Direct Compile All Files
        run: |
          cd src
          # Компилируем абсолютно все исходные файлы .c, включая сетевые модули
          mips-linux-gnu-gcc -march=mips32 -mtune=mips32 -msoft-float -O2 -static -D_GNU_SOURCE *.c -o ciadpi-lexra -lpthread
          cd ..
          mkdir -p output
          mv src/ciadpi-lexra output/

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: my-ciadpi
          path: output/ciadpi-lexra
