name: Build ciadpi for Lexra
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download ByeDPI Archive
        run: |
          mkdir -p src
          # Скачиваем стабильный tar.gz архив ветки main и распаковываем напрямую в папку src
          curl -L "https://github.com" -o byedpi.tar.gz
          tar -xzf byedpi.tar.gz -C src --strip-components=1

      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mips-linux-gnu

      - name: Compile via Make
        run: |
          cd src
          make CC=mips-linux-gnu-gcc TARGET=linux CFLAGS="-march=mips32 -mtune=mips32 -msoft-float -O2" LDFLAGS="-static"
          cd ..
          mkdir -p output
          mv src/ciadpi output/ciadpi-lexra

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: my-ciadpi
          path: output/ciadpi-lexra
