name: Build ciadpi for Lexra
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download ByeDPI Archive
        run: |
          curl -L "https://github.com/hufrea/byedpi/archive/refs/heads/main.zip" -o byedpi.zip
          unzip byedpi.zip
          mkdir -p src
          cp -r byedpi-main/* src/

      - name: Build via Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mips-linux-gnu
          cd src
          mips-linux-gnu-gcc -march=mips32 -mtune=mips32 -msoft-float -O2 -static -D_GNU_SOURCE *.c -o ciadpi-lexra -lpthread
          cd ..
          mkdir -p output
          mv src/ciadpi-lexra output/

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: my-ciadpi
          path: output/ciadpi-lexra
